global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'payment-gateway'
    static_configs:
      - targets: ['payment-gateway:8000']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']